INSERT INTO steps (id, scenario_id, idx, role, text)
VALUES
  (37, 5, 1, 'aircraft', 'Malta Ground, RYR4735, Stand 4, request taxi.'),
  (38, 5, 2, 'tower', 'RYR4735, taxi to holding point C via Victor, Uniform, Charlie, contact Tower on 135.105.'),
  (39, 5, 3, 'aircraft', 'Malta Tower, RYR4735, holding at C, ready for departure.'),
  (40, 5, 4, 'tower', 'RYR4735, roger, line-up runway 31, cleared for takeoff.'),
  (41, 5, 5, 'aircraft', 'Cleared for takeoff runway 31, RYR4735.'),
  (42, 5, 6, 'aircraft', 'Luqa Radar, RYR4735, passing 2000 feet, climbing 5000ft, on the GZO3D SID.'),

  (43, 6, 1, 'aircraft', 'Malta Ground, KMM514, Stand 5, request taxi.'),
  (44, 6, 2, 'tower', 'KMM514, taxi to holding point C via Victor, Uniform, Charlie, contact Tower on 135.105.'),
  (45, 6, 3, 'aircraft', 'Malta Tower, KMM514, holding m at C, ready for departure.'),
  (46, 6, 4, 'aircraft', 'Malta Tower, KMM514, we have a TCAS fault, request return to stand.'),
  (47, 6, 5, 'tower', 'KMM514, roger, hold position, standby.'),
  (48, 6, 6, 'tower', 'KMM514, enter runway 31, then turn left via Delta, Uniform, Victor to Stand 5, contact Ground on 121.605.'),
  (49, 6, 7, 'aircraft', 'Roger, enter runway 31, left via Delta, Uniform, Victor to Stand contact Ground 121.605, KMM514.'),

  (50, 7, 1, 'aircraft', 'Malta Ground, DLH1307, Stand 7, request taxi.'),
  (51, 7, 2, 'tower', 'DLH1307, taxi to holding point C via Victor, Uniform, Charlie, contact Tower on 135.105.'),
  (52, 7, 3, 'aircraft', 'Malta Tower, DLH1307, holding at C, ready for departure.'),
  (53, 7, 4, 'tower', 'DLH1307, line-up runway 31, cleared for takeoff.'),
  (54, 7, 5, 'aircraft', 'DLH1307 aborting takeoff due to bird strike, request assistance.'),
  (55, 7, 6, 'tower', 'DLH1307, roger, birdstrike copied, are you able to vacate runway?'),
  (56, 7, 7, 'aircraft', 'DLH1307, roger able to vacate under own power.'),
  (57, 7, 8, 'tower', 'DLH1307, vacate runway via Hotel Sierra, then Hotel, to Stand 33. Emergency services deployed.'),
  (58, 7, 9, 'aircraft', 'DLH1307 vacating runway 31 via Hotel Sierra, Hotel, to Stand 33.'),


  (59, 8, 1, 'aircraft', 'Malta Radar, KMM514, maintaining FL340, inbound ARLOS.'),
  (60, 8, 2, 'tower', 'KMM514, radio contact, maintain FL340, proceed direct EVIRA.'),
  (61, 8, 3, 'aircraft', 'Direct EVIRA, KMM514.'),

  (62, 9, 1, 'aircraft', 'PAN PAN PAN, DLH1307, we have a medical emergency.'),
  (63, 9, 2, 'tower', 'DLH1307, roger PAN PAN medical, report intentions.'),
  (64, 9, 3, 'aircraft', 'DLH1307, request diversion to Luqa.'),
  (65, 9, 4, 'tower', 'Roger, DLH1307, start descent now to FL150, current runway in use is Runway 13. You are currently 90Nm from Luqa.'),
  (66, 9, 5, 'aircraft', 'Descend to FL150 to Luqa, runway in use is Runway 13, DLH1307.'),
  (67, 9, 6, 'tower', 'When ready, report details of sick passenger.'),
  (68, 9, 7, 'aircraft', 'One passenger unconscious, male, 60yrs old, breathing difficulties, seat 16C., DLH1307. Request medical assistance.'),
  (69, 9, 8, 'tower', 'Roger, male 60yrs, unconscious, seat 16C. Medical services informed.'),
  (70, 9, 9, 'aircraft', 'Malta Radar, request further descend to Malta.'),
  (71, 9, 10, 'tower', 'DLH1307, contact Luqa Approach on 128.155.'),

  (72, 10, 1, 'tower', 'RYR4735, Malta Radar, do you read?'),
  (73, 10, 2, 'tower', 'RYR4735, Malta Radar, if you read, squawk IDENT or contact on 130.975.'),
  (74, 10, 3, 'tower', 'All stations, Malta Radar, relay to RYR4735, attempt contact on 130.975.'),
  (75, 10, 4, 'tower', 'Malta Radar, initiating radio failure procedures for RYR4735.'),
  (76, 10, 5, 'aircraft', 'Malta Radar, RYR4735, radio failure resolved, re-established contact on 135.105.'),
  (77, 10, 6, 'tower', 'RYR4735, roger, confirm FL380 and routing direct DORAT.'),
  (78, 10, 7, 'aircraft', 'Affirm, maintaining FL380, direct DORAT, RYR4735.'),
  (79, 10, 8, 'tower', 'RYR4735, continue as filed.'),
  (80, 10, 9, 'aircraft', 'Continuing as per flight plan, RYR4735.'),


  (81, 11, 1, 'aircraft', 'Malta Approach, KMM102, descending to FL150, approaching EKOLA.'),
  (82, 11, 2, 'tower', 'KMM102, radar contact. Proceed direct KEKOR, descend FL70, expect ILS approach runway 31.'),
  (83, 11, 3, 'aircraft', 'Direct KEKOR, descending to FL70, expecting ILS runway 31, KMM102.'),
  (84, 11, 4, 'tower', 'KMM102, descend to altitude 3,000 feet, via KEKOR, cleared ILS approach runway 31.'),
  (85, 11, 5, 'aircraft', 'Descending to 3,000 feet, via KEKOR, cleared ILS approach runway 31, KMM102.'),
  (86, 11, 6, 'tower', 'KMM102, continue approach with Luqa Tower on 135.105.'),
  (87, 11, 7, 'aircraft', 'Tower on 135.105, KMM102.'),

  (88, 12, 1, 'aircraft', 'Luqa Tower, DLH1307, 8 miles final runway 13.'),
  (89, 12, 2, 'tower', 'DLH1307, continue approach, caution: drone activity reported near runway threshold.'),
  (90, 12, 3, 'aircraft', 'Continuing approach, DLH1307.'),
  (91, 12, 4, 'tower', 'DLH1307, cancel approach, go around, I say again, go around. Drone close to runway.'),
  (92, 12, 5, 'aircraft', 'Cancelling approach, Going around, DLH1307.'),
  (93, 12, 6, 'tower', 'DLH1307, fly runway heading, climb to 3,000 feet.'),
  (94, 12, 7, 'aircraft', 'Runway heading, climbing to 3,000 feet, DLH1307.'),
  (95, 12, 8, 'tower', 'DLH1307, contact Luqa Approach on 128.115.'),
  (96, 12, 9, 'aircraft', 'Approach on 128.115, DLH1307.'),

  (97, 13, 1, 'aircraft', 'Malta Approach, RYR4735, descending to FL70, direct TIVOR.'),
  (98, 13, 2, 'tower', 'RYR4735, radar contact. Proceed direct LUVOS, expect CAT II ILS approach runway 31. RVR reported at 350 meters.'),
  (99, 13, 3, 'aircraft', 'Direct LUVOS, expecting CAT II ILS 31, RYR4735.'),
  (100, 13, 4, 'tower', 'RYR4735, descend to altitude 3000 feet, via LUVOS, cleared CAT II ILS approach runway 31.'),
  (101, 13, 5, 'aircraft', 'Descending to 3000 feet, via LUVOS, cleared CAT II ILS 31, RYR4735.'),
  (102, 13, 6, 'tower', 'RYR4735, contact Luqa Tower on 135.105.'),
  (103, 13, 7, 'aircraft', 'Tower on 135.105, RYR4735.');


INSERT INTO extended_steps (id, scenario_id, idx, role, text)
VALUES
  (37, 5, 1, 'aircraft', 'The pilot of RYR4735, a Ryanair Boeing 737-800 parked at Stand 4, calls Malta Ground requesting taxi clearance to the active runway.'),
  (38, 5, 2, 'tower', 'Ground control clears RYR4735 to taxi to holding point C using taxiways Victor, Uniform, and Charlie. The pilot is instructed to switch to Tower frequency 135.105 when reaching C.'),
  (39, 5, 3, 'aircraft', 'Upon arriving at holding point C, the pilot checks in on the tower frequency, reporting that the aircraft is ready for departure.'),
  (40, 5, 4, 'tower', 'Tower acknowledges RYR4735 and instructs them to line up on runway 31 and clears them for takeoff.'),
  (41, 5, 5, 'aircraft', 'The pilot reads back the clearance and begins the takeoff roll on runway 31.'),
  (42, 5, 6, 'aircraft', 'Once airborne, the pilot checks in with Luqa Radar, reporting that the aircraft is passing 2000 feet and climbing to 5000 feet via the GZO3D Standard Instrument Departure (SID).'),

  (43, 6, 1, 'aircraft', 'The pilot of KMM514, an Air Malta Airbus A320 at Stand 5, contacts Malta Ground to request taxi clearance to the active runway.'),
  (44, 6, 2, 'tower', 'Ground control issues taxi clearance to holding point C via Victor, Uniform, and Charlie, instructing the pilot to switch to Tower frequency 135.105 once there.'),
  (45, 6, 3, 'aircraft', 'KMM514 checks in with Malta Tower, reporting that they are holding short at point C and ready for departure.'),
  (46, 6, 4, 'aircraft', 'The pilot reports a TCAS fault and requests to return to the stand for technical evaluation.'),
  (47, 6, 5, 'tower', 'Tower acknowledges the request and instructs the aircraft to hold position while they coordinate the return route.'),
  (48, 6, 6, 'tower', 'Tower then instructs KMM514 to enter runway 31, backtrack, and turn left via Delta, Uniform, and Victor to return to Stand 5. The pilot is advised to contact Ground on frequency 121.605.'),
  (49, 6, 7, 'aircraft', 'The pilot confirms the routing and frequency change, beginning the taxi back to Stand 5 for further action.'),

  (50, 7, 1, 'aircraft', 'The pilot of DLH1307, a Lufthansa Airbus A321 at Stand 7, contacts Malta Ground to request taxi clearance to the active runway.'),
  (51, 7, 2, 'tower', 'Ground control instructs DLH1307 to taxi to holding point C via Victor, Uniform, and Charlie, and to contact Tower on frequency 135.105 once there.'),
  (52, 7, 3, 'aircraft', 'DLH1307 checks in with Tower after arriving at holding point C, reporting readiness for departure.'),
  (53, 7, 4, 'tower', 'Tower instructs DLH1307 to line up on runway 31 and clears the flight for takeoff.'),
  (54, 7, 5, 'aircraft', 'As the takeoff roll begins, the pilot reports a bird strike and aborts the takeoff, requesting assistance.'),
  (55, 7, 6, 'tower', 'Tower acknowledges the emergency and asks if the aircraft is able to vacate the runway under its own power.'),
  (56, 7, 7, 'aircraft', 'The pilot confirms they can vacate without assistance.'),
  (57, 7, 8, 'tower', 'Tower instructs DLH1307 to vacate runway 31 via taxiways Hotel Sierra and Hotel, proceeding to Stand 33. Emergency services are notified and dispatched.'),
  (58, 7, 9, 'aircraft', 'DLH1307 reports vacating the runway via the instructed taxiways, heading to Stand 33 for inspection.'),


  (59, 8, 1, 'aircraft', 'The pilot of KMM514, an Air Malta A320, checks in with Malta Radar while maintaining flight level 340 enroute to waypoint ARLOS.'),
  (60, 8, 2, 'tower', 'Malta Radar confirms radio contact and instructs the aircraft to proceed direct to waypoint EVIRA, maintaining current cruising level.'),
  (61, 8, 3, 'aircraft', 'The pilot acknowledges the clearance and confirms the direct routing to EVIRA.'),

  (62, 9, 1, 'aircraft', 'While enroute, the pilot of DLH1307 broadcasts a PAN PAN PAN emergency call, reporting a medical situation on board.'),
  (63, 9, 2, 'tower', 'Malta Radar acknowledges the urgency and asks DLH1307 to state their intentions.'),
  (64, 9, 3, 'aircraft', 'DLH1307 requests an immediate diversion to Luqa Airport.'),
  (65, 9, 4, 'tower', 'Malta Radar clears DLH1307 to descend to FL150, advising that the active runway is 13 and the aircraft is 90 nautical miles from the airport.'),
  (66, 9, 5, 'aircraft', 'The pilot reads back the descent clearance and confirms destination and runway.'),
  (67, 9, 6, 'tower', 'ATC requests further information on the passenger’s condition.'),
  (68, 9, 7, 'aircraft', 'The pilot reports that the affected passenger is a 60-year-old male, unconscious and experiencing breathing difficulty in seat 16C. Medical assistance is requested.'),
  (69, 9, 8, 'tower', 'Malta Radar confirms the information and notifies medical services on the ground.'),
  (70, 9, 9, 'aircraft', 'DLH1307 requests further descent to continue approach into Malta.'),
  (71, 9, 10, 'tower', 'Malta Radar hands the flight over to Luqa Approach on frequency 128.155 for continued handling.'),

  (72, 10, 1, 'tower', 'Malta Radar attempts to establish contact with RYR4735, which has stopped responding while enroute.'),
  (73, 10, 2, 'tower', 'After no response, ATC instructs the aircraft to squawk IDENT or reply on 130.975 if able to hear.'),
  (74, 10, 3, 'tower', 'Malta Radar broadcasts a general request for any nearby aircraft to assist in relaying a message to RYR4735.'),
  (75, 10, 4, 'tower', 'With no communication received, radar initiates official radio failure protocols for RYR4735.'),
  (76, 10, 5, 'aircraft', 'RYR4735 re-establishes contact on 135.105, confirming that the radio failure has been resolved.'),
  (77, 10, 6, 'tower', 'ATC acknowledges the contact and confirms current flight level and route.'),
  (78, 10, 7, 'aircraft', 'The pilot confirms they are maintaining FL380 and flying direct to waypoint DORAT.'),
  (79, 10, 8, 'tower', 'Malta Radar instructs RYR4735 to continue with the filed flight plan.'),
  (80, 10, 9, 'aircraft', 'The pilot confirms compliance and resumes normal operations.'),


  (81, 11, 1, 'aircraft', 'KMM102, a scheduled Air Malta arrival, checks in with Malta Approach, descending to FL150 and inbound to waypoint EKOLA.'),
  (82, 11, 2, 'tower', 'Approach confirms radar contact and directs the flight to proceed to waypoint KEKOR, descending to FL70, and advises that an ILS approach to runway 31 is expected.'),
  (83, 11, 3, 'aircraft', 'The pilot acknowledges the clearance and confirms the expected approach.'),
  (84, 11, 4, 'tower', 'ATC further clears KMM102 to descend to 3,000 feet via KEKOR and provides final ILS approach clearance for runway 31.'),
  (85, 11, 5, 'aircraft', 'KMM102 confirms the descent and ILS clearance.'),
  (86, 11, 6, 'tower', 'Approach instructs KMM102 to switch to Luqa Tower on frequency 135.105 to continue the approach sequence.'),
  (87, 11, 7, 'aircraft', 'The pilot acknowledges and switches frequencies as instructed.'),

  (88, 12, 1, 'aircraft', 'DLH1307, a Lufthansa A321, reports to Luqa Tower that it is on final approach, 8 miles out for runway 13.'),
  (89, 12, 2, 'tower', 'The tower instructs DLH1307 to continue approach but warns of reported drone activity near the threshold.'),
  (90, 12, 3, 'aircraft', 'The pilot confirms and continues the approach while remaining alert for possible drone hazards.'),
  (91, 12, 4, 'tower', 'Tower spots a drone hazard and instructs the aircraft to cancel the approach and go around immediately.'),
  (92, 12, 5, 'aircraft', 'DLH1307 acknowledges and begins the go-around procedure.'),
  (93, 12, 6, 'tower', 'Tower issues missed approach instructions: maintain runway heading and climb to 3,000 feet.'),
  (94, 12, 7, 'aircraft', 'The pilot confirms the heading and climb.'),
  (95, 12, 8, 'tower', 'Tower hands DLH1307 off to Luqa Approach on 128.115 for re-sequencing.'),
  (96, 12, 9, 'aircraft', 'DLH1307 confirms frequency change and contacts approach.'),

  (97, 13, 1, 'aircraft', 'RYR4735 contacts Malta Approach, reporting descent to FL70 and direct routing to waypoint TIVOR.'),
  (98, 13, 2, 'tower', 'Malta Approach confirms radar contact and directs the aircraft to LUVOS, advising a Category II ILS approach to runway 31 due to low visibility. RVR is reported at 350 meters.'),
  (99, 13, 3, 'aircraft', 'The pilot acknowledges the instructions and prepares for the CAT II approach.'),
  (100, 13, 4, 'tower', 'Approach clears the flight to descend to 3000 feet via LUVOS and authorizes the CAT II ILS approach to runway 31.'),
  (101, 13, 5, 'aircraft', 'RYR4735 confirms descent and clearance for the low-visibility ILS approach.'),
  (102, 13, 6, 'tower', 'ATC instructs the aircraft to contact Luqa Tower on 135.105 to continue the final approach.'),
  (103, 13, 7, 'aircraft', 'The pilot switches to the tower frequency and continues the final segment of the approach.');
