INSERT INTO steps (id, scenario_id, idx, role, text)
VALUES
       (2, 1, 2, 'aircraft', 'Malta Ground, KM102, request taxi to runway 31.'),
       (3, 1, 3, 'tower', 'KM102, taxi to holding point C1 via Alpha and Charlie, contact Tower on 118.3 at C1.'),
       (4, 1, 4, 'aircraft', 'Malta Tower, KM102, holding short runway 31 at C1, ready for departure.'),
       (5, 1, 5, 'tower', 'KM102, runway 31 cleared for takeoff.'),
       (6, 1, 6, 'aircraft', 'Cleared for takeoff runway 31, KM102.'),
       (7, 1, 7, 'aircraft', 'Malta Tower, KM102, airborne, passing 1000 feet.'),
       (8, 1, 8, 'tower', 'KM102, roger, contact Malta Radar on 128.15.'),
       (9, 1, 9, 'aircraft', 'Malta Radar, KM102, climbing through 1500 feet.'),

       (11, 2, 2, 'aircraft', 'Malta Ground, RYR4735, request taxi to runway 31, aware of wet runway conditions.'),
       (12, 2, 3, 'tower',
        'RYR4735, taxi to holding point C1 via Alpha and Charlie. Caution: braking action reported medium. Contact Tower on 118.3 at C1.'),
       (13, 2, 4, 'aircraft',
        'Malta Tower, RYR4735, holding short runway 31 at C1, ready for departure. We are prepared for reduced braking.'),
       (14, 2, 5, 'tower', 'RYR4735, wind 290 at 8, runway 31 cleared for takeoff. Use caution for standing water.'),
       (15, 2, 6, 'aircraft', 'Cleared for takeoff runway 31, RYR4735. Caution acknowledged.'),
       (16, 2, 7, 'aircraft', 'Malta Tower, RYR4735, airborne, positive climb, gear up.'),
       (17, 2, 8, 'tower', 'RYR4735, roger, radar contact, contact Malta Radar on 128.15.'),
       (18, 2, 9, 'aircraft', 'Malta Radar, RYR4735, climbing through 1500 feet, moderate turbulence encountered.'),

       (20, 3, 2, 'aircraft', 'Malta Ground, LH1276, request taxi to runway 31.'),
       (21, 3, 3, 'tower', 'LH1276, taxi to holding point C1 via Alpha and Charlie, contact Tower on 118.3 at C1.'),
       (22, 3, 4, 'aircraft', 'Malta Tower, LH1276, holding short runway 31 at C1, ready for departure.'),
       (23, 3, 5, 'tower', 'LH1276, runway 31 cleared for takeoff.'),
       (24, 3, 6, 'aircraft', 'Cleared for takeoff runway 31, LH1276.'),
       (25, 3, 7, 'aircraft',
        'Malta Tower, LH1276, bird strike, engine 2 affected, declaring PAN PAN, request immediate return.'),
       (26, 3, 8, 'tower',
        'LH1276, roger PAN PAN, turn left heading 270, climb not above 3000 feet, cleared to return runway 31. Fire and rescue alerted.'),
       (27, 3, 9, 'aircraft', 'Turning left heading 270, not above 3000 feet, returning runway 31, LH1276.'),

       (29, 4, 2, 'aircraft', 'Malta Ground, KM102, request taxi to runway 31.'),
       (30, 4, 3, 'tower', 'KM102, taxi to holding point C1 via Alpha and Charlie, contact Tower on 118.3 at C1.'),
       (31, 4, 4, 'aircraft', 'Malta Tower, KM102, holding short runway 31 at C1, ready for departure.'),
       (32, 4, 5, 'tower', 'KM102, runway 31 cleared for takeoff.'),
       (33, 4, 6, 'aircraft', 'Cleared for takeoff runway 31, KM102.'),
       (34, 4, 7, 'aircraft', 'Malta Tower, KM102, engine failure, declaring MAYDAY, requesting immediate return.'),
       (35, 4, 8, 'tower',
        'KM102, roger MAYDAY, turn right heading 090, maintain 2000 feet, cleared visual approach runway 31. Emergency services are standing by.'),
       (36, 4, 9, 'aircraft',
        'Turning right heading 090, maintain 2000 feet, cleared visual approach runway 31, KM102.');

INSERT INTO extended_steps (id, scenario_id, idx, role, text)
VALUES
       (2, 1, 2, 'aircraft',
        'The pilot of KM102 contacts Malta Ground, requesting clearance to taxi to runway 31 for departure.'),
       (3, 1, 3, 'tower',
        'Malta Ground responds to KM102, instructing the aircraft to taxi to holding point C1 using taxiways Alpha and Charlie, and to switch to Tower frequency 118.3 upon arrival at C1.'),
       (4, 1, 4, 'aircraft',
        'KM102 reports to Malta Tower, indicating it is holding short of runway 31 at C1 and is ready for takeoff.'),
       (5, 1, 5, 'tower',
        'Malta Tower clears KM102 for takeoff on runway 31, giving the necessary authorization for departure.'),
       (6, 1, 6, 'aircraft', 'The pilot of KM102 acknowledges the clearance and begins the takeoff roll on runway 31.'),
       (7, 1, 7, 'aircraft',
        'Once airborne, KM102 reports to Malta Tower, confirming that the aircraft is climbing and passing 1000 feet.'),
       (8, 1, 8, 'tower',
        'Malta Tower acknowledges KM102’s report and instructs the aircraft to contact Malta Radar on frequency 128.15.'),
       (9, 1, 9, 'aircraft',
        'KM102 checks in with Malta Radar, confirming it is climbing through 1500 feet, continuing its ascent.'),

       (11, 2, 2, 'aircraft',
        'RYR4735 contacts Malta Ground, requesting taxi clearance to runway 31, while acknowledging the wet runway conditions.'),
       (12, 2, 3, 'tower',
        'Malta Ground instructs RYR4735 to taxi to holding point C1 via Alpha and Charlie, warning of medium braking action, and advising a switch to Tower on 118.3 at C1.'),
       (13, 2, 4, 'aircraft',
        'RYR4735 confirms it is holding short of runway 31 at C1 and is prepared for departure, acknowledging the reduced braking conditions.'),
       (14, 2, 5, 'tower',
        'Malta Tower clears RYR4735 for takeoff on runway 31, advising caution due to standing water.'),
       (15, 2, 6, 'aircraft',
        'The pilot of RYR4735 acknowledges the clearance and begins the takeoff roll, keeping in mind the wet runway conditions.'),
       (16, 2, 7, 'aircraft',
        'After becoming airborne, RYR4735 reports a positive rate of climb and retracts the landing gear.'),
       (17, 2, 8, 'tower',
        'Malta Tower acknowledges the climb and advises RYR4735 to contact Malta Radar on frequency 128.15.'),
       (18, 2, 9, 'aircraft',
        'RYR4735 checks in with Malta Radar, reporting a climb through 1500 feet and encountering moderate turbulence.'),

       (20, 3, 2, 'aircraft', 'LH1276 requests clearance from Malta Ground to taxi to runway 31.'),
       (21, 3, 3, 'tower',
        'Malta Ground authorizes LH1276 to taxi to holding point C1 via Alpha and Charlie, advising to switch to Tower on 118.3 at C1.'),
       (22, 3, 4, 'aircraft', 'LH1276 confirms it is holding short of runway 31 at C1, ready for takeoff.'),
       (23, 3, 5, 'tower', 'Malta Tower clears LH1276 for takeoff on runway 31.'),
       (24, 3, 6, 'aircraft', 'The pilot of LH1276 acknowledges clearance and initiates the takeoff roll.'),
       (25, 3, 7, 'aircraft',
        'After becoming airborne, LH1276 reports a bird strike, declaring PAN PAN due to engine 2 being affected, and requests an immediate return.'),
       (26, 3, 8, 'tower',
        'Malta Tower acknowledges the PAN PAN declaration, providing instructions for a left turn to heading 270, climbing no higher than 3000 feet, and confirming that emergency services are alerted.'),
       (27, 3, 9, 'aircraft', 'LH1276 confirms compliance with instructions and begins the return to the airfield.'),

       (29, 4, 2, 'aircraft', 'KM102 requests taxi clearance to runway 31 from Malta Ground.'),
       (30, 4, 3, 'tower',
        'Malta Ground grants KM102 clearance to taxi to holding point C1 via Alpha and Charlie, advising a switch to Tower on 118.3 at C1.'),
       (31, 4, 4, 'aircraft', 'KM102 reports ready for departure, holding short of runway 31 at C1.'),
       (32, 4, 5, 'tower', 'Malta Tower clears KM102 for takeoff on runway 31.'),
       (33, 4, 6, 'aircraft', 'The pilot of KM102 acknowledges clearance and begins takeoff.'),
       (34, 4, 7, 'aircraft', 'KM102 reports an engine failure and declares MAYDAY, requesting immediate return.'),
       (35, 4, 8, 'tower',
        'Malta Tower acknowledges the MAYDAY, providing instructions for a right turn heading 090, maintaining 2000 feet, with emergency services on standby.'),
       (36, 4, 9, 'aircraft', 'KM102 confirms the instructions and begins the emergency return.');

